# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test7777' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test7777
pod "PGFramework"
  target 'Test7777Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test7777UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
